name: Daily NBA Prediction

on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install torch pandas nba_api beautifulsoup4 numpy

      - name: Train and Predict
        run: |
          python train.py
          python predict_today.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "NBA-AI-Bot"
          git config --global user.email "bot@github.com"
          git add index.html nba_model_2026.pth
          git pull origin main --rebase -X theirs
          git diff --quiet && git diff --staged --quiet || (git commit -m "AI Update: $(date)" && git push origin main)
